# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replication_receiver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replication_receiver.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1areplication_receiver.proto\"%\n\x12ReplicationRequest\x12\x0f\n\x07message\x18\x01 \x02(\t\"&\n\x13ReplicationResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x32W\n\x13ReplicationReceiver\x12@\n\x11replicate_message\x12\x13.ReplicationRequest\x1a\x14.ReplicationResponse\"\x00'
)




_REPLICATIONREQUEST = _descriptor.Descriptor(
  name='ReplicationRequest',
  full_name='ReplicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ReplicationRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=67,
)


_REPLICATIONRESPONSE = _descriptor.Descriptor(
  name='ReplicationResponse',
  full_name='ReplicationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ReplicationResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['ReplicationRequest'] = _REPLICATIONREQUEST
DESCRIPTOR.message_types_by_name['ReplicationResponse'] = _REPLICATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReplicationRequest = _reflection.GeneratedProtocolMessageType('ReplicationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATIONREQUEST,
  '__module__' : 'replication_receiver_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationRequest)
  })
_sym_db.RegisterMessage(ReplicationRequest)

ReplicationResponse = _reflection.GeneratedProtocolMessageType('ReplicationResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATIONRESPONSE,
  '__module__' : 'replication_receiver_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationResponse)
  })
_sym_db.RegisterMessage(ReplicationResponse)



_REPLICATIONRECEIVER = _descriptor.ServiceDescriptor(
  name='ReplicationReceiver',
  full_name='ReplicationReceiver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='replicate_message',
    full_name='ReplicationReceiver.replicate_message',
    index=0,
    containing_service=None,
    input_type=_REPLICATIONREQUEST,
    output_type=_REPLICATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICATIONRECEIVER)

DESCRIPTOR.services_by_name['ReplicationReceiver'] = _REPLICATIONRECEIVER

# @@protoc_insertion_point(module_scope)
