# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from shared import replication_receiver_pb2 as replication__receiver__pb2


class ReplicationReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.replicate_message = channel.unary_unary(
                '/ReplicationReceiver/replicate_message',
                request_serializer=replication__receiver__pb2.ReplicationRequest.SerializeToString,
                response_deserializer=replication__receiver__pb2.ReplicationResponse.FromString,
                )


class ReplicationReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def replicate_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'replicate_message': grpc.unary_unary_rpc_method_handler(
                    servicer.replicate_message,
                    request_deserializer=replication__receiver__pb2.ReplicationRequest.FromString,
                    response_serializer=replication__receiver__pb2.ReplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReplicationReceiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReplicationReceiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def replicate_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ReplicationReceiver/replicate_message',
            replication__receiver__pb2.ReplicationRequest.SerializeToString,
            replication__receiver__pb2.ReplicationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
